//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Green_Enviro_App.src.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StreetAddress { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNum { get; set; }
        public string TaxNum { get; set; }
        public string RegNum { get; set; }
        public byte[] Logo { get; set; }
    }
}
