//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Green_Enviro_App.src.DataAccess
{
    using System;
    using System.Collections.Generic;
    

    public partial class Customer
    {

        public Customer() { }

        public Customer(Customer customer) 
        {
            this.CustomerNumber = customer.CustomerNumber;
            this.ID = customer.ID;
            this.Name = customer.Name;
            this.Surname = customer.Surname;
            this.Cell = customer.Cell;
            this.Address = customer.Address;
        }

        public int CustomerNumber { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Cell { get; set; }
        public string Address { get; set; }
        public byte[] IDPicture { get; set; }
    }
}
